name: factorio
description: for testing the space age apworld
game: 'Factorio: Space Age'
requires:
  version: 0.6.4
  game:
    'Factorio: Space Age': 1.0.0 # Version of the world required for this yaml to work as expected.
'Factorio: Space Age': {}
